local_backend: true
backend:
  name: github
  repo: YOUR_GITHUB_USERNAME/asianhornet-site
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.astro"
        label: "Home"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Description", name: "description", widget: "string", required: false}
          - {label: "Content", name: "body", widget: "markdown", required: false}
      - file: "src/pages/resources.astro"
        label: "Resources"
        name: "resources"
        fields:
          - {label: "Body", name: "body", widget: "markdown", required: false}
      - file: "src/pages/about.astro"
        label: "About"
        name: "about"
        fields:
          - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "posts"
    label: "Updates"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
